Repository Goorm-IT/NyanYumUnivServer, pull requests merged in 2022-05, with the labels that each got.

#50 (진행)(NYU-56)[Sprint3] NYU-MAIN 작업 PR
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/StoreController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/PageInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreSearchInfo.java
  NYU-Main/src/main/resources/mapper/storeMapper.xml
Labels: In Progress, Review Required, teamin

#51 (완료)[NYU-60][Sprint3]Review Service Delete API
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/ReviewController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/ReviewService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/ReviewServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/ReviewInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/ReviewSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/ReviewMapper.java
  NYU-Main/src/main/resources/mapper/ReviewMapper.xml
Labels: Sugyeong

#52 (완료)[NYU-60][Sprint3]Review Service Delete API to develop
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/ReviewController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/ReviewService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/ReviewServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/ReviewInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/ReviewSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/ReviewMapper.java
  NYU-Main/src/main/resources/mapper/MenuMapper.xml
  NYU-Main/src/main/resources/mapper/ReviewMapper.xml
  NYU-Main/src/main/resources/mapper/UserMapper.xml
  NYU-Main/src/main/resources/mapper/storeMapper.xml
Labels: Done, Sugyeong

#53 (완료)[NYU-77][Sprint3]Like Service API
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/LikeController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/LikeService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/LikeServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/LikeInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/LikeSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/LikeMapper.java
Labels: Sugyeong

#54 (완료)[NYU-77][Sprint3]Like Service API to develop
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/LikeController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/LikeService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/LikeServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/LikeInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/LikeSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/LikeMapper.java
  NYU-Main/src/main/resources/mapper/LikeMapper.xml
Labels: Done, Review Required
