Repository Goorm-IT/NyanYumUnivServer, pull requests merged in 2022-04, with the labels that each got.

#23 (진행)(NYU-54)IMG-MAIN 연결
  .gitignore
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/misc.xml
  NYU-IMG/pom.xml
  NYU-IMG/src/main/java/META-INF/MANIFEST.MF
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/NyuImgApplication.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/config/SwaggerConfig.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/service/ImageService.java
  NYU-IMG/src/main/resources/application.properties
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/UserService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/UserServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/UserMapper.java
  NYU-Main/src/main/resources/mapper/UserMapper.xml
  logs/NYU-MAIN.2022-03-31.0.log.gz
  logs/NYU-MAIN.log
Labels: In Progress, Sugyeong

#24 (진행)(NYU-54)Swagger error fix
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/config/SwaggerConfig.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/controller/ImageController.java
  NYU-IMG/src/test/java/com/nyanyumserver/nyuimg/NyuImgApplicationTests.java
Labels: In Progress, Sugyeong

#25 (진행)(NYU-54)Swagger error fix
  .gitignore
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/misc.xml
  NYU-IMG/pom.xml
  NYU-IMG/src/main/java/META-INF/MANIFEST.MF
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/NyuImgApplication.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/config/SwaggerConfig.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/controller/ImageController.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/service/ImageService.java
  NYU-IMG/src/main/resources/application.properties
  NYU-IMG/src/test/java/com/nyanyumserver/nyuimg/NyuImgApplicationTests.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/UserService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/UserServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/UserMapper.java
  NYU-Main/src/main/resources/mapper/UserMapper.xml
  logs/NYU-MAIN.2022-03-31.0.log.gz
  logs/NYU-MAIN.log
Labels: In Progress, Sugyeong

#26 (완료)[NYU-18][Sprint1]관리자 페이지 모델 수정
  .gitignore
  .idea/compiler.xml
  .idea/misc.xml
  NYU_Manage/NYU_Manage/__pycache__/__init__.cpython-38.pyc
  NYU_Manage/NYU_Manage/__pycache__/settings.cpython-38.pyc
  NYU_Manage/NYU_Manage/__pycache__/urls.cpython-38.pyc
  NYU_Manage/NYU_Manage/__pycache__/wsgi.cpython-38.pyc
  NYU_Manage/NYU_Manage/settings.py
  NYU_Manage/NYU_Manage/urls.py
  NYU_Manage/manage_admin/__pycache__/__init__.cpython-38.pyc
  NYU_Manage/manage_admin/__pycache__/admin.cpython-38.pyc
  NYU_Manage/manage_admin/__pycache__/apps.cpython-38.pyc
  NYU_Manage/manage_admin/__pycache__/models.cpython-38.pyc
  NYU_Manage/manage_admin/admin.py
  NYU_Manage/manage_admin/migrations/0002_delete_menu.py
  NYU_Manage/manage_admin/migrations/0003_menu.py
  NYU_Manage/manage_admin/migrations/0004_delete_menu.py
  NYU_Manage/manage_admin/migrations/0005_menu.py
  NYU_Manage/manage_admin/migrations/__pycache__/0001_initial.cpython-38.pyc
  NYU_Manage/manage_admin/migrations/__pycache__/0002_delete_menu.cpython-38.pyc
  NYU_Manage/manage_admin/migrations/__pycache__/0003_menu.cpython-38.pyc
  NYU_Manage/manage_admin/migrations/__pycache__/0004_delete_menu.cpython-38.pyc
  NYU_Manage/manage_admin/migrations/__pycache__/0005_menu.cpython-38.pyc
  NYU_Manage/manage_admin/migrations/__pycache__/__init__.cpython-38.pyc
  NYU_Manage/manage_admin/models.py
Labels: Done, Sugyeong

#27 (완료)[NYU-18][Sprint1]관리자 페이지 모델 적용 및 커스터마이징
  .gitignore
  .idea/compiler.xml
  .idea/misc.xml
  NYU_Manage/NYU_Manage/__pycache__/__init__.cpython-38.pyc
  NYU_Manage/NYU_Manage/__pycache__/settings.cpython-38.pyc
  NYU_Manage/NYU_Manage/__pycache__/urls.cpython-38.pyc
  NYU_Manage/NYU_Manage/__pycache__/wsgi.cpython-38.pyc
  NYU_Manage/NYU_Manage/settings.py
  NYU_Manage/NYU_Manage/urls.py
  NYU_Manage/manage_admin/__pycache__/__init__.cpython-38.pyc
  NYU_Manage/manage_admin/__pycache__/admin.cpython-38.pyc
  NYU_Manage/manage_admin/__pycache__/apps.cpython-38.pyc
  NYU_Manage/manage_admin/__pycache__/models.cpython-38.pyc
  NYU_Manage/manage_admin/admin.py
  NYU_Manage/manage_admin/migrations/0002_delete_menu.py
  NYU_Manage/manage_admin/migrations/0003_menu.py
  NYU_Manage/manage_admin/migrations/0004_delete_menu.py
  NYU_Manage/manage_admin/migrations/0005_menu.py
  NYU_Manage/manage_admin/migrations/__pycache__/0001_initial.cpython-38.pyc
  NYU_Manage/manage_admin/migrations/__pycache__/0002_delete_menu.cpython-38.pyc
  NYU_Manage/manage_admin/migrations/__pycache__/0003_menu.cpython-38.pyc
  NYU_Manage/manage_admin/migrations/__pycache__/0004_delete_menu.cpython-38.pyc
  NYU_Manage/manage_admin/migrations/__pycache__/0005_menu.cpython-38.pyc
  NYU_Manage/manage_admin/migrations/__pycache__/__init__.cpython-38.pyc
  NYU_Manage/manage_admin/models.py
Labels: Done, Sugyeong

#32 (진행)(NYU-61)NYU-IMG store 이미지 API
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/controller/ImageController.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/service/ImageService.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/service/impl/ImageServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Common/CommonConst.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/AdminController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/StoreController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/DB/nyuDB.sql
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/UserService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/AdminServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/StoreServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/UserServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/MenuInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/UserInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/UserSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/UserMapper.java
  NYU-Main/src/main/resources/fcm.json
  NYU-Main/src/main/resources/mapper/UserMapper.xml
  NYU-Main/src/main/resources/mapper/storeMapper.xml
  NYU-Main/target/classes/application.yml
Labels: In Progress, Sugyeong

#36 (완료)[NYU-74][Sprint2]NYU-IMG_Swagger_Error_Fix
  NYU-IMG/pom.xml
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/config/SwaggerConfig.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/controller/ImageController.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/service/ImageService.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/service/impl/ImageServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
Labels: Done, Sugyeong

#37 (완료)[NYU-61][Sprint2]NYU-Main Adding Store API
  .idea/misc.xml
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/service/impl/ImageServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/StoreController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/ImageService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/StoreService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/ImageServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/StoreServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/UserServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/StoreMapper.java
  NYU-Main/src/main/resources/mapper/storeMapper.xml
  NYU-Main/target/classes/application.yml
Labels: Done, Sugyeong

#38 (완료)[NYU-61][Sprint2]NYU-Main 가게 추가 API
  .idea/misc.xml
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/service/impl/ImageServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/StoreController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/ImageService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/StoreService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/ImageServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/StoreServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/UserServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/StoreMapper.java
  NYU-Main/src/main/resources/mapper/storeMapper.xml
  NYU-Main/target/classes/application.yml
Labels: Done, Sugyeong

#42 Eureka 미업로드 파일 커밋 & PR
  NYU-Eureka/pom.xml
  NYU-Eureka/src/main/java/com/nyu/eureka/NyuEurekaApplication.java
  NYU-Eureka/src/main/resources/application.yml
Labels: bug, In Progress, teamin

#46 (진행)[NYU-60][Sprint3]Review Service 기본 API 구현 to develop
  .gitignore
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/controller/ImageController.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/service/impl/ImageServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Common/CommonConst.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Common/CommonResponse.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/ReviewController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/StoreController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/ReviewService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/ImageServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/ReviewServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/ReviewInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/ReviewSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/ReviewMapper.java
  NYU-Main/src/main/resources/mapper/ReviewMapper.xml
  NYU-Main/src/main/resources/mapper/UserMapper.xml
Labels: In Progress, Sugyeong, Review Required

#47 어노테이션 변경
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/MenuInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/PageInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/PostInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/PostSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/ReviewInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/ReviewSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/UserInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/UserSearchInfo.java
Labels: Review Required, teamin
