Repository Goorm-IT/NyanYumUnivServer, pull requests merged in 2022-03, with the labels that each got.

#8 [NYU-18]#in-progress[Sprint1]admin page db migration
  .gitignore
  NYU_Manage/NYU_Manage/__init__.py
  NYU_Manage/NYU_Manage/__pycache__/__init__.cpython-38.pyc
  NYU_Manage/NYU_Manage/__pycache__/settings.cpython-38.pyc
  NYU_Manage/NYU_Manage/__pycache__/urls.cpython-38.pyc
  NYU_Manage/NYU_Manage/__pycache__/wsgi.cpython-38.pyc
  NYU_Manage/NYU_Manage/asgi.py
  NYU_Manage/NYU_Manage/settings.py
  NYU_Manage/NYU_Manage/urls.py
  NYU_Manage/NYU_Manage/wsgi.py
  NYU_Manage/manage.py
  NYU_Manage/manage_admin/__init__.py
  NYU_Manage/manage_admin/__pycache__/__init__.cpython-38.pyc
  NYU_Manage/manage_admin/__pycache__/admin.cpython-38.pyc
  NYU_Manage/manage_admin/__pycache__/apps.cpython-38.pyc
  NYU_Manage/manage_admin/__pycache__/models.cpython-38.pyc
  NYU_Manage/manage_admin/admin.py
  NYU_Manage/manage_admin/apps.py
  NYU_Manage/manage_admin/migrations/0001_initial.py
  NYU_Manage/manage_admin/migrations/__init__.py
  NYU_Manage/manage_admin/migrations/__pycache__/0001_initial.cpython-38.pyc
  NYU_Manage/manage_admin/migrations/__pycache__/__init__.cpython-38.pyc
  NYU_Manage/manage_admin/models.py
  NYU_Manage/manage_admin/tests.py
  NYU_Manage/manage_admin/views.py
Labels: In Progress, Sugyeong

#9 (진행)(NYU-34)[Sprint1]NYU-MAIN LogBack 적용
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/AdminController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/StoreController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/AdminService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/AdminServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/UserInfo.java
  NYU-Main/src/main/resources/mapper/AdminMapper.xml
  NYU-Main/src/main/resources/mapper/UserMapper.xml
Labels: In Progress, teamin

#10 Kyle
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Common/CommonConst.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Config/SwaggerConfiguration.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/MainController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/StoreController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/StoreService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/StoreServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/PageInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/UserInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/AdminMapper.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/StoreMapper.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/storeMapper.java
  NYU-Main/src/main/resources/application.properties
  NYU-Main/src/main/resources/application.yml
  NYU-Main/src/main/resources/mapper/storeMapper.xml
Labels: In Progress, teamin

#13 (진행)(NYU-30)(NYU-31)[sprint1]
  NYU-Main/pom.xml
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Common/CommonConst.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/StoreController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/StoreService.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Service/impl/StoreServiceImpl.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/PageInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/VO/StoreSearchInfo.java
  NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/mapper/StoreMapper.java
  NYU-Main/src/main/resources/mapper/storeMapper.xml
Labels: In Progress, teamin

#15 (Hot Fix) db config file settings
  .gitignore
  NYU-Main/src/main/resources/application.yml
Labels: Done, Sugyeong

#19 (진행)(NYU-16)[Sprint1]httpStatus 세분화
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/Controller/ImageController.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/Global/error/GlobalExceptionHandler.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/Global/error/exception/ErrorCode.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/Global/status/StatusResponse.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/Service/ImageService.java
  NYU-IMG/src/main/java/com/nyanyumserver/nyuimg/Service/impl/ImageServiceImpl.java
  NYU-IMG/target/classes/META-INF/spring-configuration-metadata.json
  NYU-IMG/target/classes/application.properties
  NYU-IMG/target/classes/application.yml
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/Controller/ImageController.class
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/Global/error/ErrorResponse$FieldError.class
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/Global/error/ErrorResponse.class
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/Global/error/GlobalExceptionHandler.class
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/Global/error/exception/BusinessException.class
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/Global/error/exception/EntityNotFoundException.class
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/Global/error/exception/ErrorCode.class
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/Global/error/exception/InvalidValueException.class
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/Global/status/StatusCode.class
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/Global/status/StatusResponse.class
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/NyuImgApplication.class
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/Service/ImageService.class
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/Service/component/Component.class
  NYU-IMG/target/classes/com/nyanyumserver/nyuimg/Service/impl/ImageServiceImpl.class
  NYU-IMG/target/test-classes/com/nyanyumserver/nyuimg/NyuImgApplicationTests.class
Labels: In Progress, Sugyeong
